version: '3.8'

services:
  mcp-example:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-example:latest
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000